[package]
name = "rewrk3"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"